FROM node

RUN npm install --location=global nodemon

WORKDIR /app

COPY /package.json .

RUN npm install 

COPY . .

#ENV REACT_APP_NAME=myName

EXPOSE 3000

#docker build -t tailwind-fcc -f Dockerfile.dev .
CMD [ "npm", "run", "dev" ]